/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewPackage;

import ControlPackage.InvoiceButtonsActionListener;
import ControlPackage.InvoiceSelectionListener;
import ModelPackage.H_TableModel;
import ModelPackage.Header_SIG_app;
import ModelPackage.Line_SIG_app;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author weam1
 */
public class SIG_Application_Frame extends javax.swing.JFrame   {

    /**
     * Creates new form SIG_Application_Frame
     */
    public SIG_Application_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        HeaderTable = new javax.swing.JTable();
        CreateINVbtn = new javax.swing.JButton();
        DeleteINVbtn = new javax.swing.JButton();
        InvoiceNumber = new javax.swing.JLabel();
        InvoiceDate = new javax.swing.JLabel();
        EnterCustomerName = new javax.swing.JLabel();
        InvoiceTotal = new javax.swing.JLabel();
        EnterNum = new javax.swing.JLabel();
        EnterDate = new javax.swing.JLabel();
        EnterCustmoer = new javax.swing.JLabel();
        EnterTotalInv = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LineTable = new javax.swing.JTable();
        SaveINVbtn = new javax.swing.JButton();
        CancelINVbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customernamefield = new javax.swing.JTextField();
        invoicedatefield = new javax.swing.JTextField();
        invoicenumberlabel = new javax.swing.JLabel();
        invoicetotallabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        Loadmenu = new javax.swing.JMenuItem();
        Savemenu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        HeaderTable.getSelectionModel().addListSelectionListener(selListener);
        jScrollPane1.setViewportView(HeaderTable);

        CreateINVbtn.setText("Create New Invoice");
        CreateINVbtn.addActionListener(actionListener);
        CreateINVbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateINVbtnActionPerformed(evt);
            }
        });

        DeleteINVbtn.setText("Delete Invoice");
        DeleteINVbtn.addActionListener(actionListener);

        InvoiceNumber.setText("Invoice Number");

        InvoiceDate.setText("Invoice Date");

        EnterCustomerName.setText("Customer Name");

        InvoiceTotal.setText("Invoice Total");

        LineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(LineTable);

        SaveINVbtn.setText("Save");
        SaveINVbtn.addActionListener(actionListener);

        CancelINVbtn.setText("Cancel");
        CancelINVbtn.addActionListener(actionListener);

        FileMenu.setText("File");

        Loadmenu.setText("Load File");
        Loadmenu.addActionListener(actionListener);
        Loadmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadmenuActionPerformed(evt);
            }
        });
        FileMenu.add(Loadmenu);

        Savemenu.setText("Save File");
        Savemenu.addActionListener(actionListener);
        Savemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavemenuActionPerformed(evt);
            }
        });
        FileMenu.add(Savemenu);

        jMenuBar1.add(FileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(CreateINVbtn)
                .addGap(65, 65, 65)
                .addComponent(DeleteINVbtn)
                .addGap(213, 213, 213)
                .addComponent(SaveINVbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(CancelINVbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(InvoiceTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InvoiceDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InvoiceNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EnterCustomerName))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invoicetotallabel)
                            .addComponent(invoicenumberlabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(customernamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                                .addComponent(invoicedatefield)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EnterNum)
                            .addComponent(EnterDate)
                            .addComponent(EnterCustmoer)
                            .addComponent(EnterTotalInv))
                        .addGap(455, 455, 455)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 374, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(invoicenumberlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InvoiceNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnterNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(invoicedatefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InvoiceDate))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(EnterDate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(EnterCustmoer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EnterTotalInv))
                                            .addComponent(jLabel1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EnterCustomerName)
                                            .addComponent(customernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(InvoiceTotal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(invoicetotallabel)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateINVbtn)
                    .addComponent(DeleteINVbtn)
                    .addComponent(SaveINVbtn)
                    .addComponent(CancelINVbtn))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SavemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavemenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavemenuActionPerformed

    private void LoadmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadmenuActionPerformed

    private void CreateINVbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateINVbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateINVbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIG_Application_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIG_Application_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIG_Application_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIG_Application_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIG_Application_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelINVbtn;
    private javax.swing.JButton CreateINVbtn;
    private javax.swing.JButton DeleteINVbtn;
    private javax.swing.JLabel EnterCustmoer;
    private javax.swing.JLabel EnterCustomerName;
    private javax.swing.JLabel EnterDate;
    private javax.swing.JLabel EnterNum;
    private javax.swing.JLabel EnterTotalInv;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JTable HeaderTable;
    private javax.swing.JLabel InvoiceDate;
    private javax.swing.JLabel InvoiceNumber;
    private javax.swing.JLabel InvoiceTotal;
    private javax.swing.JTable LineTable;
    private javax.swing.JMenuItem Loadmenu;
    private javax.swing.JButton SaveINVbtn;
    private javax.swing.JMenuItem Savemenu;
    private javax.swing.JTextField customernamefield;
    private javax.swing.JTextField invoicedatefield;
    private javax.swing.JLabel invoicenumberlabel;
    private javax.swing.JLabel invoicetotallabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private InvoiceButtonsActionListener actionListener=new InvoiceButtonsActionListener(this);
    private ArrayList<Header_SIG_app> Invsarray;
    public static SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    private H_TableModel headertablemodel;
    private InvoiceSelectionListener selListener =new InvoiceSelectionListener(this);
    private ArrayList<Line_SIG_app> LineInvsarray;

    public ArrayList<Line_SIG_app> getLineInvsarray() {
        return LineInvsarray;
    }

    public void setLineInvsarray(ArrayList<Line_SIG_app> LineInvsarray) {
        this.LineInvsarray = LineInvsarray;
    }

    
    
   

    public void setInvsarray(ArrayList<Header_SIG_app> Invsarray) {
        this.Invsarray = Invsarray;
    }

    public ArrayList<Header_SIG_app> getInvsarray() {
        return Invsarray;
    }
    
    
    public Header_SIG_app getInvobject (int code){
        for (Header_SIG_app inv : Invsarray) {
            if (inv.getNumberOfInvoice() == code) {
                return inv;
            }
        }
        return null;
    }

    public H_TableModel getHeadertablemodel() {
        return headertablemodel;
    }

    public void setHeadertablemodel(H_TableModel headertablemodel) {
        this.headertablemodel = headertablemodel;
    }

    public JTable getHeaderTable() {
        return HeaderTable;
    }

    public void setHeaderTable(JTable HeaderTable) {
        this.HeaderTable = HeaderTable;
    }

    public JTable getLineTable() {
        return LineTable;
    }

    public void setLineTable(JTable LineTable) {
        this.LineTable = LineTable;
    }

    public JLabel getInvoiceDate() {
        return InvoiceDate;
    }

    public JLabel getInvoiceNumber() {
        return InvoiceNumber;
    }

    public JLabel getInvoiceTotal() {
        return InvoiceTotal;
    }

    public JLabel getEnterCustomerName() {
        return EnterCustomerName;
    }

    public InvoiceButtonsActionListener getActionListener() {
        return actionListener;
    }

    public JTextField getCustomernamefield() {
        return customernamefield;
    }

    public JTextField getInvoicedatefield() {
        return invoicedatefield;
    }

    public JLabel getInvoicenumberlabel() {
        return invoicenumberlabel;
    }

    public JLabel getInvoicetotallabel() {
        return invoicetotallabel;
    }
    
    

    
    

    
    }
